/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopkeeperRouteImport } from './routes/shopkeeper'
import { Route as RoleRouteImport } from './routes/role'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as IndexRouteImport } from './routes/index'

const ShopkeeperRoute = ShopkeeperRouteImport.update({
  id: '/shopkeeper',
  path: '/shopkeeper',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/role': typeof RoleRoute
  '/shopkeeper': typeof ShopkeeperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer': typeof CustomerRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/role': typeof RoleRoute
  '/shopkeeper': typeof ShopkeeperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer': typeof CustomerRoute
  '/language': typeof LanguageRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/role': typeof RoleRoute
  '/shopkeeper': typeof ShopkeeperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer'
    | '/language'
    | '/login'
    | '/merchant'
    | '/role'
    | '/shopkeeper'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer'
    | '/language'
    | '/login'
    | '/merchant'
    | '/role'
    | '/shopkeeper'
  id:
    | '__root__'
    | '/'
    | '/customer'
    | '/language'
    | '/login'
    | '/merchant'
    | '/role'
    | '/shopkeeper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRoute: typeof CustomerRoute
  LanguageRoute: typeof LanguageRoute
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRoute
  RoleRoute: typeof RoleRoute
  ShopkeeperRoute: typeof ShopkeeperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopkeeper': {
      id: '/shopkeeper'
      path: '/shopkeeper'
      fullPath: '/shopkeeper'
      preLoaderRoute: typeof ShopkeeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRoute: CustomerRoute,
  LanguageRoute: LanguageRoute,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRoute,
  RoleRoute: RoleRoute,
  ShopkeeperRoute: ShopkeeperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
